name: dart_discord
description: Discord webhook dart interface.
version: 1.0.0
repository: https://github.com/williambulin/dart_discord

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.0
